# encoding: utf-8
namespace :db do
  desc 'Set initial role assignments'
  task :set_initial_roles => :environment do
    Person.where(name: 'Aaron Baker').first.update_attributes(role: 'Developer')
    Person.where(name: 'Aaron Christy').first.update_attributes(role: 'Developer')
    Person.where(name: 'Abhaya Shenoy').first.update_attributes(role: 'Developer')
    Person.where(name: 'Adam McCrea').first.update_attributes(role: 'Developer')
    Person.where(name: 'Alan Gardner').first.update_attributes(role: 'Developer')
    Person.where(name: 'Alan Yeo').first.update_attributes(role: 'Developer')
    Person.where(name: 'Alex Burkhart').first.update_attributes(role: 'Developer')
    Person.where(name: 'Alex Kim').first.update_attributes(role: 'Designer')
    Person.where(name: 'Alfonso Cora').first.update_attributes(role: 'Developer')
    Person.where(name: 'Ally Reeves').first.update_attributes(role: 'Designer')
    Person.where(name: 'Alvaro Gil').first.update_attributes(role: 'Developer')
    Person.where(name: 'Aly Fluckey').first.update_attributes(role: 'Developer')
    Person.where(name: 'Andi Plantenberg (Contractor)').first.update_attributes(role: 'Designer')
    Person.where(name: 'Andrew Robinson').first.update_attributes(role: 'Business Development')
    Person.where(name: 'Anil Podduturi').first.update_attributes(role: 'Principal')
    Person.where(name: 'Ariena Kaneshima').first.update_attributes(role: 'Support Staff')
    Person.where(name: 'Brian Flanagan').first.update_attributes(role: 'Designer')
    Person.where(name: 'Bruno Aguirre').first.update_attributes(role: 'Developer')
    Person.where(name: 'Bryan Cunningham - Apprentice').first.update_attributes(role: 'Apprentice')
    Person.where(name: 'Carin Meier').first.update_attributes(role: 'Managing Director')
    Person.where(name: 'Carl Coryell-Martin').first.update_attributes(role: 'Principal')
    Person.where(name: 'Cecilia Castro').first.update_attributes(role: 'Support Staff')
    Person.where(name: 'Chandu Tennety').first.update_attributes(role: 'Developer')
    Person.where(name: 'Chris Westra').first.update_attributes(role: 'Developer')
    Person.where(name: 'Corey Innis').first.update_attributes(role: 'Principal')
    Person.where(name: 'Dan Williams').first.update_attributes(role: 'Principal')
    Person.where(name: 'Daniel Cadenas').first.update_attributes(role: 'Developer')
    Person.where(name: 'Daniel Grieve').first.update_attributes(role: 'Developer')
    Person.where(name: 'Daniel Riedel').first.update_attributes(role: 'General & Administrative')
    Person.where(name: 'Daryl Manning').first.update_attributes(role: 'Managing Director')
    Person.where(name: 'Dave Anderson').first.update_attributes(role: 'Developer')
    Person.where(name: 'David Bland').first.update_attributes(role: 'Principal')
    Person.where(name: 'Deb Schultz').first.update_attributes(role: 'Managing Director')
    Person.where(name: 'Delisa Mason').first.update_attributes(role: 'Developer')
    Person.where(name: 'Derek Briggs').first.update_attributes(role: 'Designer')
    Person.where(name: 'Diego Algorta').first.update_attributes(role: 'Managing Director')
    Person.where(name: 'Diego Garcia').first.update_attributes(role: 'Developer')
    Person.where(name: 'Doug Rohrer').first.update_attributes(role: 'Developer')
    Person.where(name: 'Evan Henshaw-Plath').first.update_attributes(role: 'General & Administrative')
    Person.where(name: 'Federico Baña').first.update_attributes(role: 'Developer')
    Person.where(name: 'Felipe Pérez').first.update_attributes(role: 'Developer')
    Person.where(name: 'Felix Flores').first.update_attributes(role: 'Developer')
    Person.where(name: 'Fernando Briano').first.update_attributes(role: 'Developer')
    Person.where(name: 'Gabe').first.update_attributes(role: 'Developer')
    Person.where(name: 'Geoff Lane').first.update_attributes(role: 'Developer')
    Person.where(name: 'Germán Monfort').first.update_attributes(role: 'Developer')
    Person.where(name: 'Giff Constable').first.update_attributes(role: 'General & Administrative')
    Person.where(name: 'Gina Winkler').first.update_attributes(role: 'Principal')
    Person.where(name: 'Gustavo Armagno').first.update_attributes(role: 'Developer')
    Person.where(name: 'Ian McFarland').first.update_attributes(role: 'General & Administrative')
    Person.where(name: 'Jaime Dávila').first.update_attributes(role: 'Developer')
    Person.where(name: 'Jason Voegele').first.update_attributes(role: 'Developer')
    Person.where(name: 'Jeff Gothelf').first.update_attributes(role: 'Principal')
    Person.where(name: 'Jerry Nummi').first.update_attributes(role: 'Designer')
    Person.where(name: 'Jim Weirich').first.update_attributes(role: 'Principal')
    Person.where(name: 'John Andrews').first.update_attributes(role: 'Developer')
    Person.where(name: 'John Colvin').first.update_attributes(role: 'Developer')
    Person.where(name: 'Jonathan Irwin').first.update_attributes(role: 'Managing Director')
    Person.where(name: 'Jono Mallanyk').first.update_attributes(role: 'Designer')
    Person.where(name: 'Josh Seiden').first.update_attributes(role: 'Managing Director')
    Person.where(name: 'Juanita Sabapathy').first.update_attributes(role: 'Support Staff')
    Person.where(name: 'Ken Barker').first.update_attributes(role: 'General & Administrative')
    Person.where(name: 'Kris Hedges - Apprentice').first.update_attributes(role: 'Apprentice')
    Person.where(name: 'Lauren Woodrick').first.update_attributes(role: 'Designer')
    Person.where(name: 'Lucía Escanellas').first.update_attributes(role: 'Developer')
    Person.where(name: 'Luke Chamberlin').first.update_attributes(role: 'Designer')
    Person.where(name: 'Marcelo Nieves').first.update_attributes(role: 'Developer')
    Person.where(name: 'Mark Connell').first.update_attributes(role: 'Developer')
    Person.where(name: 'María Pérez').first.update_attributes(role: 'Designer')
    Person.where(name: 'Matt Jones').first.update_attributes(role: 'Developer')
    Person.where(name: 'Mike Caprio').first.update_attributes(role: 'Developer')
    Person.where(name: 'Mike Danko').first.update_attributes(role: 'Developer')
    Person.where(name: 'Mike Doel').first.update_attributes(role: 'Managing Director')
    Person.where(name: 'Mike Long').first.update_attributes(role: 'Developer')
    Person.where(name: 'Mike Mazur').first.update_attributes(role: 'Principal')
    Person.where(name: 'Mohan Krishnan').first.update_attributes(role: 'Developer')
    Person.where(name: 'Mukund Lakshman').first.update_attributes(role: 'Developer')
    Person.where(name: 'Nicole Zhu').first.update_attributes(role: 'Developer')
    Person.where(name: 'Nicolás Barrera').first.update_attributes(role: 'Developer')
    Person.where(name: 'Paul Henrich').first.update_attributes(role: 'Developer')
    Person.where(name: 'Paul Wilson').first.update_attributes(role: 'Managing Director')
    Person.where(name: 'Peter Aitken').first.update_attributes(role: 'Developer')
    Person.where(name: 'Peter Shanley').first.update_attributes(role: 'Principal')
    Person.where(name: 'Raven Keller').first.update_attributes(role: 'Designer')
    Person.where(name: 'Rika Nakazawa').first.update_attributes(role: 'Business Development')
    Person.where(name: 'Rizwan Reza').first.update_attributes(role: 'Developer')
    Person.where(name: 'Ryan Stocker').first.update_attributes(role: 'Developer')
    Person.where(name: 'Sam McAfee').first.update_attributes(role: 'Principal')
    Person.where(name: 'Scott Barron').first.update_attributes(role: 'Managing Director')
    Person.where(name: 'Scott Burwinkel').first.update_attributes(role: 'Developer')
    Person.where(name: 'Scott Walker').first.update_attributes(role: 'Developer')
    Person.where(name: 'Sebastian Heit').first.update_attributes(role: 'Designer')
    Person.where(name: 'Shelley Byers').first.update_attributes(role: 'General & Administrative')
    Person.where(name: 'Steve Arnold (contractor)').first.update_attributes(role: 'Designer')
    Person.where(name: 'Stuart Nelson').first.update_attributes(role: 'Developer')
    Person.where(name: 'Swayam Narain').first.update_attributes(role: 'Apprentice')
    Person.where(name: 'Tami Carpenter').first.update_attributes(role: 'Support Staff')
    Person.where(name: 'Tim Lombardo').first.update_attributes(role: 'Product Manager')
    Person.where(name: 'Tomek Maszkowski').first.update_attributes(role: 'Developer')
    Person.where(name: 'Tommy Sullivan').first.update_attributes(role: 'Developer')
    Person.where(name: 'Tony Schneider').first.update_attributes(role: 'Developer')
    Person.where(name: 'Wei Lu').first.update_attributes(role: 'Developer')
    Person.where(name: 'Winston Teo').first.update_attributes(role: 'Developer')
    Person.where(name: 'Wren Lanier').first.update_attributes(role: 'Principal')
    Person.where(name: 'Yoz Grahame').first.update_attributes(role: 'Developer')
    Person.where(name: 'Zi (Huong Vu)').first.update_attributes(role: 'Developer')
  end
end
